##################################################################################################
# CREATE VIRTUALSERVER - mailhog
##################################################################################################
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: crapi-web-vs-http
  namespace: crapi
spec:
  host: mypremiumdealership.dev.local
  upstreams:
  - name: crapi-web
    service: crapi-web
    port: 80
  routes:
    - path: /
      action:
        pass: crapi-web
