##################################################################################################
# UPDATE SERVICE - mailhog
##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: crapi
    meta.helm.sh/release-namespace: crapi
  labels:
    app: mailhog
    app.kubernetes.io/managed-by: Helm
    release: crapi
  name: mailhog-web
  namespace: crapi
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 8025
    protocol: TCP
    targetPort: 8025
  selector:
    app: mailhog
##################################################################################################
# CREATE VIRTUALSERVER - mailhog
##################################################################################################
---
apiVersion: k8s.nginx.org/v1alpha1
kind: TransportServer
metadata:
  name: mailhog-tcp
  namespace: crapi
spec:
  listener:
    name: mailhog-tcp
    protocol: TCP
  upstreams:
  - name: mailhog-app
    service: mailhog-web
    port: 8025
  action:
    pass: mailhog-app
